name: bomber_man
description: "bomber_man"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
#  nakama: ^1.1.0
  uuid: ^4.5.1
  provider: ^6.1.2
  collection: ^1.18.0
  bonfire: ^3.10.2
  peerdart: ^0.5.6
#  flame_behaviors: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0





flutter:

  
  uses-material-design: true

  
  assets:
    - assets/map/
    - assets/images/spritesheet.png
    - assets/images/wall_tile.png
    - assets/images/explode_sheet.png
    - assets/images/tiled/tiles.json
    - assets/images/tiled/tiles.png
    - assets/images/tiled/village_10.json
#    - images/a_dot_burr.jpeg
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
